### ISSUE TITLE
oauth2-proxy example

### ISSUE THREAD

**Issue by mts-dyt** [ejhayes/bull-monitor#251]
Hello,
Can we have an example of integration with OAUTH2 proxy?
I managed to add new variables related to the proxy.
When accessing app, I now have the oauth-proxy page and it redirects me to the IdP (keycloak for me).
I can see that the authentification is sucessfull as they are messages like:
```
{<USER>@<DOMAIN> [2023/07/13 15:10:47] [AuthSuccess] Authenticated via OAuth2
```

But then it redirect me to the URL like `https://<URL>/oauth2/callback?state=XXXX&session_state=XXXX` and I have a 502 badGateway

**Comment by ejhayes** [comment]
@mts-dyt this seems to indicate that your redirect url (env variable `OAUTH2_PROXY_REDIRECT_URL`) is having problems. Can you provide more information? Also are you running this locally or in somewhere else?

**Comment by mts-dyt** [comment]
I managed to get it working :)
Here is an example for KeyCloak:
```
USE_OAUTH2_PROXY: 1
OAUTH2_PROXY_OIDC_ISSUER_URL: <KEYCLOAK_URL_REALM>
OAUTH2_PROXY_UPSTREAMS:  "http://localhost:8081" (Alternate_port)
OAUTH2_PROXY_CLIENT_ID: <CLIENT_ID>
OAUTH2_PROXY_CLIENT_SECRET: <CLIENT_SECRET>
OAUTH2_PROXY_COOKIE_SECRET: <RANDOM_STRING>
OAUTH2_PROXY_FORCE_CODE_CHALLENGE_METHOD: S256
OAUTH2_PROXY_PROVIDER: keycloak-oidc
OAUTH2_PROXY_EMAIL_DOMAINS: *
OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: true
```

You need to create a client in Keycloak side with a secret + create an audience mapper as described here: https://www.keycloak.org/docs/latest/server_admin/#_audience_hardcoded
