### ISSUE TITLE
Allow Redis with a password

### ISSUE THREAD

**Issue by roderik** [ejhayes/bull-monitor#3]
Our redis instance uses a password, the nestjs-redis module allows to use this. It would be great if you would enable this in the docker image

```
export default {
    host: process.env.REDIS_HOST,
    port: parseInt(process.env.REDIS_PORT),
    db: parseInt(process.env.REDIS_DB),
    password: process.env.REDIS_PASSWORD,
    keyPrefix: process.env.REDIS_PRIFIX,
}
```

**Comment by ejhayes** [comment]
Thanks for pointing this out @roderik. PR is welcome otherwise I will aim to get this added this week.
