### ISSUE TITLE
How to integrate with Grafana

### ISSUE THREAD

**Issue by nadishan** [ejhayes/bull-monitor#6]
Hi, I want to integrate this with Grafana dashboard( https://grafana.com/grafana/dashboards/14538 (import into grafana using id: 14538)). How can I do it?

**Comment by ejhayes** [comment]
Hey @nadishan I've updated the readme with some notes on this. High level overview though:

- Setup grafana
- Add prometheus data source to grafana
- Ensure that prometheus is setup to scrape metrics from bull-monitor
- Import the dashboard in grafana using the ID (and point it at prometheus)

If you pull down the repo and run `npm run services:start:all` that'll setup everything locally for you to experiment around with.
